version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dtbbanking-postgres
    restart: always
    environment:
      POSTGRES_DB: dtbbanking
      POSTGRES_USER: dtb
      POSTGRES_PASSWORD: dtbpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dtb"]
      interval: 10s
      timeout: 5s
      retries: 5

  customer-service:
    build: ./customer-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  account-service:
    build: ./account-service
    ports:
      - "8082:8082"
    depends_on:
      - customer-service
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  card-service:
    build: ./card-service
    ports:
      - "8083:8083"
    depends_on:
      - account-service
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8083/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
